### ISSUE TITLE
Recurso de validação de formulário (Captcha)

### ISSUE THREAD

**Issue by marcello** [cercomp/weby#12]
https://softifes.cercomp.ufg.br/issues/619

Implementar recurso de captcha para impedir robôs de explorarem indevidamente os recursos.

Comentários Arthur:

Algumas coisa devem ser levadas em consideração aqui:

Segurança
Simplicidade
Acessibilidade ( Versão com som por exemplo )
Também devemos analisar quais formulários vão utilizar (feedback; sign up?; disponibilizar para qualquer componente que queira usar,
ou agregar o captcha ao componente?)

Lista de gems -> ruby-toolbox
Discussão no stackoverflow

Comentários Nícolas:

Arthur,

foi sugerido a utilização do captcha estilo operação matemática simples, pode avaliar ele em comparação com outros e ver qual é o mais ideal?

Quanto a implementação acho que podemos implementar inicialmente em três momentos:

feedback/new
login
signup (estudar e implementar posteriormente politica de exclusão de contas nunca utilizadas, verificar se depois disso ainda é necessário utilizar o captcha)
no caso do login e signup vai estar implementado no código, no caso do feedback/new já pensando nas engines acho que pode ser uma configuração que desabilita ou não o captcha.

**Comment by robeiro** [comment]
Que tal agente usar essa: https://github.com/emotionLoop/visualCaptcha-rubyGem

**Comment by marcello** [comment]
@robeiro pode implementar em uma branch para vermos o resultado? Lembrando que só temos duas entradas de dados publico (sem autenticação), o fale conosco e o cadastro de usuário.

**Comment by arthurguima** [comment]
Esse visual Captcha é o mesmo utilizado no ENEM,
