### ISSUE TITLE
Redefinir  a estrutura do menu lateral de modo que se possa diferenciar o que é link do que não é

### ISSUE THREAD

**Issue by arthurguima** [cercomp/weby#187]
O que é Link e o que apenas um divisor do menu? Extensões por exemplo é um divisor e ao mesmo tempo é um link.  Extensões, por exemplo, é um link e divisor de contexto ao mesmo tempo.

![image](https://cloud.githubusercontent.com/assets/910049/4751574/b1660512-5a9f-11e4-899e-229ea83cbc27.png)

Veja esse menu que estou trabalhando: 

![image](https://cloud.githubusercontent.com/assets/910049/4751592/e6d4afe6-5a9f-11e4-9e80-9a27f105e9bb.png) ![image](https://cloud.githubusercontent.com/assets/910049/4751599/0e5eb5c0-5aa0-11e4-8540-17926d3f1532.png)

Ainda incluo a sugestão da seta que esconde o menu na lateral:

![image](https://cloud.githubusercontent.com/assets/910049/4751652/b81e98aa-5aa0-11e4-93db-b0e0c60e812c.png)

**Comment by marcello** [comment]
Iremos implementar o LTEAdmin.
