### ISSUE TITLE
Criar menus rápidos na tela inicial:

### ISSUE THREAD

**Issue by arthurguima** [cercomp/weby#191]
Veja o exemplo do wordpress:

![image](https://cloud.githubusercontent.com/assets/910049/4752022/a54012e0-5aa5-11e4-8e82-459e0650b2b6.png)

Sugestão mais simples:

![image](https://cloud.githubusercontent.com/assets/910049/4752030/b7bb8fc6-5aa5-11e4-835b-bb4a7d0e1a9b.png)

**Comment by leo-souza** [comment]
Feito
