### ISSUE TITLE
Data de atualização da notícia incorreta

### ISSUE THREAD

**Issue by leo-souza** [cercomp/weby#210]
A data de atualização da página está sendo mostrada incorreta.
Como os campos texto estão na tabela pages_i18ns o updated_at correto está nessa tabela, já que o rails nem atualiza a tabela pages. (Caso os attributos modificados forem só os que tem i18n)
Esse comportamento se aplica a todos o models com i18n

**Comment by marcello** [comment]
@robeiro isso já foi corrigido em um dos seus commits?

**Comment by robeiro** [comment]
:+1:  @marcello sim foi corrigido no commit: 23485def5d0c39a3711b050dcb6fa83f573ded2b
