### ISSUE TITLE
Pequenos ajustes

### ISSUE THREAD

**Issue by marcello** [cercomp/weby#218]
- [x] Formulários: remover as duas colunas, labels ao lado dos inputs para labels em cima dos inputs (coluna única).
- [x] Formulários: permitir expandir campo texto dos formulários horizontalmente e verticalmente.
- [x] Imagens: imprimir um fundo cinza ou invés de branco na pré-visualização das imagens.
- [x] I18n: verificar porque a aba de i18n em inglês vem primeiro do que a de português nos componentes.
- [x] Estilos: permitir redimensionar campo de estilos (css) verticalmente e horizontalmente, se possível habilitar outras funcionalidades do codemirror como: autocompletion, search interface, fullscreen e vim bindings.

**Comment by robeiro** [comment]
Só ficou faltando colocar o vim bindings, já que não seria funcional para todos os usuários!!
