### ISSUE TITLE
Pesquisa de filtro para relatório da newsletter

### ISSUE THREAD

**Issue by marcello** [cercomp/weby#300]
Pesquisa de filtro para relatório da newsletter não está funcionando.

![captura de tela de 2018-05-23 12-02-46](https://user-images.githubusercontent.com/12605/40433004-5bb564fc-5e81-11e8-9aec-8f78f0bc2bae.png)

**Comment by marcello** [comment]
Na "Lista de emails" quantidade por página também não está funcionando.

**Comment by leo-souza** [comment]
corrigido, vai subir pra produção no proximo deploy
