### ISSUE TITLE
Internacionalização de componentes HTML

### ISSUE THREAD

**Issue by mateuswetah** [cercomp/weby#303]
Olá pessoal!
Estou trabalhando no site do FGSL deste ano (http://2018.fgsl.net/). Estamos tentando fazer o site disponível em inglês para possibilitar patrocínio internacional. O processo tem side bem simples, ativei a opção de ter o site em inglês e fui traduzindo menus, artigos etc... Tudo bem intuitivo, até que descobri que o esquema de ter uma aba pra escrever a versão inglês não aparece pros componentes customizados HTML. Infelizmente, nossa Home Page foi majoritariamente feita customizada. 

Vocês teriam alguma sugestão pra contornar isso?

**Comment by leo-souza** [comment]
@mateuswetah já está na master
