### ISSUE TITLE
Criar componente adicionar estilo CSS

### ISSUE THREAD

**Issue by andreyestevao** [cercomp/weby#327]
Criar componente que permita salvar código CSS. O componente deve ter como parâmetros o nome do estilo e o código, tornando a formatação para o usuário mais prática. A intenção é que o designer prepare o estilo uma vez e o usuário produtor de conteúdo aplique os estilos a qualquer componente, seja texto imagem, audio, etc. Cada site deve ter acesso apenas aos seus estilos, não é necessário (para este momento) deixar estilos prontos entre sites.

**Comment by leo-souza** [comment]
Já existe a funcionalidade de Estilos para esse fim
